### ISSUE TITLE
referral link!

### ISSUE THREAD

**Issue by rkhyd** [bradx954/woocommerce-points-and-rewards-referral-extension#1]
Where would this referral link/email shortcode generated? please advice.

**Comment by bradx954** [comment]
You put "[woocommerce_refferal_form]" on what ever page you wan't the form to be. The html code for the form is generated on line 100 "function html_form_code()".

**Comment by rkhyd** [comment]
thank you for the reply. is it possible to show the success message without refreshing the page! Kindly see here. http://www.conceptbox.wpwithus.com/get-rewards/

**Comment by bradx954** [comment]
You could modify the form to do ajax post.
